# Render manifest for web + worker services (example)
services:
  - type: web
    name: aem-validator-web
    env: docker
    plan: free
    branch: main
    buildCommand: ''
    startCommand: 'gunicorn app.app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120'
  - type: worker
    name: aem-validator-worker
    env: docker
    plan: free
    branch: main
    startCommand: 'rq worker -u $REDIS_URL default'
