services:
  - type: web
    name: qa-packet-validator
    env: docker
    plan: free
    autoDeploy: true
    build:
      commands:
        - apt-get update && apt-get install -y --no-install-recommends tesseract-ocr poppler-utils && rm -rf /var/lib/apt/lists/*